/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoEditingRouteImport } from './routes/video-editing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CodingRouteImport } from './routes/coding'
import { Route as CapcutCourseRouteImport } from './routes/capcut-course'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnrollCapcutRouteImport } from './routes/enroll.capcut'

const VideoEditingRoute = VideoEditingRouteImport.update({
  id: '/video-editing',
  path: '/video-editing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingRoute = CodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => rootRouteImport,
} as any)
const CapcutCourseRoute = CapcutCourseRouteImport.update({
  id: '/capcut-course',
  path: '/capcut-course',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollCapcutRoute = EnrollCapcutRouteImport.update({
  id: '/enroll/capcut',
  path: '/enroll/capcut',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/capcut-course': typeof CapcutCourseRoute
  '/coding': typeof CodingRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/video-editing': typeof VideoEditingRoute
  '/enroll/capcut': typeof EnrollCapcutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/capcut-course': typeof CapcutCourseRoute
  '/coding': typeof CodingRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/video-editing': typeof VideoEditingRoute
  '/enroll/capcut': typeof EnrollCapcutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/capcut-course': typeof CapcutCourseRoute
  '/coding': typeof CodingRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/pending': typeof PendingRoute
  '/register': typeof RegisterRoute
  '/video-editing': typeof VideoEditingRoute
  '/enroll/capcut': typeof EnrollCapcutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai'
    | '/capcut-course'
    | '/coding'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/pending'
    | '/register'
    | '/video-editing'
    | '/enroll/capcut'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ai'
    | '/capcut-course'
    | '/coding'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/pending'
    | '/register'
    | '/video-editing'
    | '/enroll/capcut'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai'
    | '/capcut-course'
    | '/coding'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/pending'
    | '/register'
    | '/video-editing'
    | '/enroll/capcut'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AiRoute: typeof AiRoute
  CapcutCourseRoute: typeof CapcutCourseRoute
  CodingRoute: typeof CodingRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  PendingRoute: typeof PendingRoute
  RegisterRoute: typeof RegisterRoute
  VideoEditingRoute: typeof VideoEditingRoute
  EnrollCapcutRoute: typeof EnrollCapcutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-editing': {
      id: '/video-editing'
      path: '/video-editing'
      fullPath: '/video-editing'
      preLoaderRoute: typeof VideoEditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding': {
      id: '/coding'
      path: '/coding'
      fullPath: '/coding'
      preLoaderRoute: typeof CodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capcut-course': {
      id: '/capcut-course'
      path: '/capcut-course'
      fullPath: '/capcut-course'
      preLoaderRoute: typeof CapcutCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll/capcut': {
      id: '/enroll/capcut'
      path: '/enroll/capcut'
      fullPath: '/enroll/capcut'
      preLoaderRoute: typeof EnrollCapcutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AiRoute: AiRoute,
  CapcutCourseRoute: CapcutCourseRoute,
  CodingRoute: CodingRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  PendingRoute: PendingRoute,
  RegisterRoute: RegisterRoute,
  VideoEditingRoute: VideoEditingRoute,
  EnrollCapcutRoute: EnrollCapcutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
